### ISSUE TITLE
Crash When Opening Inventory.

### ISSUE THREAD

**Issue by EdTheDog** [AgriCraft/AgriCraft#1159]
Minecraft : 1.12.2 or forge 14.23.4.2727 Minecraft 1.12.2
Agricraft : 2.12.0-1.12.0-a4
InfintyLib :  1.12.2

Description: So since updating a lot of my mods I have been having this crash, Now whenever I check the crash file it always has to do something with Agricraft... But Agricraft and InfintyLib have not been updated at all yet the crash log still says it is its fault. Keep in mind I don't really know how to read crash logs but that's just from what I can tell. If Someone knows what mod is incompatible with Agricraft then please say because that would be a big help! :)

Sorry about long crash log... :P
Crashlog: 
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.17.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 7/3/18 4:36 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: jline/internal/Preconditions
	at com.infinityraider.agricraft.api.v1.soil.IAgriSoil.isVarient(IAgriSoil.java:42)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.lambda$null$1(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement$$Lambda$2153/1071059596.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.lambda$hasValidSoil$2(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement$$Lambda$2152/1114501281.test(Unknown Source)
	at java.util.Optional.filter(Optional.java:178)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.hasValidSoil(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.isMet(GrowthRequirement.java:121)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.isFertile(TileEntityCrop.java:345)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.spawn(TileEntityCrop.java:381)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.onGrowthTick(TileEntityCrop.java:65)
	at com.infinityraider.agricraft.blocks.BlockCrop$$Lambda$2142/92872869.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.infinityraider.agricraft.blocks.BlockCrop.func_180650_b(BlockCrop.java:91)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: jline.internal.Preconditions
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infinityraider.agricraft.api.v1.soil.IAgriSoil.isVarient(IAgriSoil.java:42)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.lambda$null$1(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement$$Lambda$2153/1071059596.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.lambda$hasValidSoil$2(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement$$Lambda$2152/1114501281.test(Unknown Source)
	at java.util.Optional.filter(Optional.java:178)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.hasValidSoil(GrowthRequirement.java:87)
	at com.infinityraider.agricraft.farming.growthrequirement.GrowthRequirement.isMet(GrowthRequirement.java:121)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.isFertile(TileEntityCrop.java:345)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.spawn(TileEntityCrop.java:381)
	at com.infinityraider.agricraft.tiles.TileEntityCrop.onGrowthTick(TileEntityCrop.java:65)
	at com.infinityraider.agricraft.blocks.BlockCrop$$Lambda$2142/92872869.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.infinityraider.agricraft.blocks.BlockCrop.func_180650_b(BlockCrop.java:91)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)

-- Affected level --
Details:
	Level name: Creative World
	All players: 1 total; [EntityPlayerMP['ComputerEric'/76, l='Creative World', x=3.19, y=100.00, z=-22.94]]
	Chunk stats: ServerChunkCache: 305 Drop: 0
	Level seed: -4118139035396000629
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;90*minecraft:air,10*minecraft:concrete;1;village
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 695760 game time, 2682 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 58623 (now: false), thunder time: 108110 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1660383496 bytes (1583 MB) / 3422552064 bytes (3264 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2727 Optifine OptiFine_1.12.2_HD_U_E1 118 mods loaded, 118 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                  | Source                                          | Signature                                |
	|:--------- |:----------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.4.2727.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.4.2727             | forge-1.12.2-14.23.4.2727.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | foamfixcore             | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | obfuscate               | 0.2.4                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | opencomputers|core      | 1.7.2.67                 | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | infinitylib             | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                          | None                                     |
	| UCHIJAAAA | agricraft               | 2.12.0-1.12.0-a4         | agricraft-2.12.0-1.12.0-a4.jar                  | None                                     |
	| UCHIJAAAA | appliedenergistics2     | rv6-alpha-1              | appliedenergistics2-rv6-alpha-1.jar             | None                                     |
	| UCHIJAAAA | psi                     | r1.1-59                  | Psi-r1.1-59.jar                                 | None                                     |
	| UCHIJAAAA | quark                   | r1.4-125                 | Quark-r1.4-125.jar                              | None                                     |
	| UCHIJAAAA | autoreglib              | 1.3-18                   | AutoRegLib-1.3-18.jar                           | None                                     |
	| UCHIJAAAA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | jei                     | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                       | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | bhc                     | 1.1.1                    | baubley-heart-canisters-1.12.2-1.1.1.jar        | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCHIJAAAA | betterbuilderswands     | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | bibliocraft             | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAA | bookshelf               | 2.3.552                  | Bookshelf-1.12.2-2.3.552.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | chameleon               | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | chameleoncreepers       | 1.4.1                    | chameleoncreepers-1.4.1-1.12.jar                | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.2.0.345                | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks           | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chiselsandbits          | 14.17                    | chiselsandbits-14.17.jar                        | None                                     |
	| UCHIJAAAA | clumps                  | 3.1.1                    | Clumps-3.1.1.jar                                | None                                     |
	| UCHIJAAAA | redstoneflux            | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                | 4.5.2                    | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld               | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | colytra                 | 1.0.4.3                  | colytra-1.12.2-1.0.4.3.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | compactmachines3        | 3.0.12                   | compactmachines3-1.12.2-3.0.12-b215.jar         | None                                     |
	| UCHIJAAAA | asielib                 | 1.0.0                    | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| UCHIJAAAA | opencomputers           | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar             | None                                     |
	| UCHIJAAAA | tesla                   | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | theoneprobe             | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                     | None                                     |
	| UCHIJAAAA | computronics            | 1.6.5                    | Computronics-1.12.1-1.6.5.jar                   | None                                     |
	| UCHIJAAAA | conarm                  | 1.0.1.2                  | conarm-1.12.2-1.0.1.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | cookingforblockheads    | 6.4.40                   | CookingForBlockheads_1.12.2-6.4.40.jar          | None                                     |
	| UCHIJAAAA | craftelytra             | 1.2                      | CraftableElytra-1.1.jar                         | None                                     |
	| UCHIJAAAA | darkutils               | 1.8.211                  | DarkUtils-1.12.2-1.8.211.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | doggytalents            | 1.14.2.318               | Doggy+Talents-1.12.2-1.14.2.318-universal.jar   | None                                     |
	| UCHIJAAAA | elevatorid              | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
	| UCHIJAAAA | enderstorage            | 2.4.4.132                | EnderStorage-1.12.2-2.4.4.132-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | valkyrielib             | 1.12.2-2.0.11a           | valkyrielib-1.12.2-2.0.11a.jar                  | None                                     |
	| UCHIJAAAA | environmentalmaterials  | @EM_VERSION@             | environmentalmaterials-1.12.2-1.0.11a.jar       | None                                     |
	| UCHIJAAAA | environmentaltech       | 1.12.2-2.0.11a           | environmentaltech-1.12.2-2.0.11a.jar            | None                                     |
	| UCHIJAAAA | etlunar                 | 1.12.2-2.0.11a           | etlunar-1.12.2-2.0.11a.jar                      | None                                     |
	| UCHIJAAAA | extracells              | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                 | None                                     |
	| UCHIJAAAA | shadowmc                | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCHIJAAAA | extrarails              | 1.3.0                    | ExtraRails-1.12-1.3.0.jar                       | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                      | extrautils2-1.12-1.7.6.jar                      | None                                     |
	| UCHIJAAAA | zerocore                | 1.12-0.1.2.2             | zerocore-1.12-0.1.2.2.jar                       | None                                     |
	| UCHIJAAAA | bigreactors             | 1.12.2-0.4.5.49          | ExtremeReactors-1.12.2-0.4.5.49.jar             | None                                     |
	| UCHIJAAAA | foamfix                 | 0.9.9.1-1.12.2           | foamfix-0.9.9.1-1.12.2-anarchy.jar              | None                                     |
	| UCHIJAAAA | forgelin                | 1.7.4                    | Forgelin-1.7.4.jar                              | None                                     |
	| UCHIJAAAA | forgemultipartcbe       | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe           | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe   | 2.4.2.60                 | ForgeMultipart-1.12.2-2.4.2.60-universal.jar    | None                                     |
	| UCHIJAAAA | globalxp                | v1.4                     | globalxp-1.12.x-v1.4.jar                        | None                                     |
	| UCHIJAAAA | grapplemod              | 1.12.2-v10               | grapplemod-v10-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | hammercore              | 1.9.9.17                 | HammerCore-1.12.2-1.9.9.17.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | ichunutil               | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.14                   | tesla-core-lib-1.12.2-1.0.14.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.10.2-178.jar       | None                                     |
	| UCHIJAAAA | ironbackpacks           | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCHIJAAAA | justenoughbuttons       | 1.12-1.2                 | justenoughbuttons-1.12.2-1.2.2-5.jar            | None                                     |
	| UCHIJAAAA | jeresources             | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| UCHIJAAAA | kythsopmoss             | 0.1                      | kythsopmoss-0.2.jar                             | None                                     |
	| UCHIJAAAA | malisiscore             | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHIJAAAA | malisisdoors            | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHIJAAAA | mcjtylib_ng             | 3.0.2                    | mcjtylib-1.12-3.0.2.jar                         | None                                     |
	| UCHIJAAAA | mrtjpcore               | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| UCHIJAAAA | naturescompass          | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJAAAA | nhc                     | 4.0.3                    | NHCore-1.12-4.0.3.jar                           | None                                     |
	| UCHIJAAAA | norecipebook            | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar              | None                                     |
	| UCHIJAAAA | notes                   | 1.1.1                    | Notes-1.12-1.1.1.jar                            | None                                     |
	| UCHIJAAAA | thaumcraft              | 6.1.BETA17               | Thaumcraft-1.12.2-6.1.BETA17.jar                | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion        | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | omlib                   | 3.0.0-148                | omlib-1.12.2-3.0.0-148.jar                      | None                                     |
	| UCHIJAAAA | openmodularturrets      | 3.0.1-257                | openmodularturrets-1.12.2-3.0.1-257.jar         | None                                     |
	| UCHIJAAAA | openprinter             | 0.1.0.2                  | OpenPrinter-1.12.2-0.1.0.2.jar                  | None                                     |
	| UCHIJAAAA | p455w0rdslib            | 2.0.29                   | p455w0rdslib-1.12-2.0.29.jar                    | None                                     |
	| UCHIJAAAA | harvestcraft            | 1.12.2t                  | Pam's+HarvestCraft+1.12.2t.jar                  | None                                     |
	| UCHIJAAAA | portalgun               | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                      | None                                     |
	| UCHIJAAAA | projectred-core         | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| UCHIJAAAA | projectred-integration  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-transmission | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-fabrication  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar      | None                                     |
	| UCHIJAAAA | projectred-illumination | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar         | None                                     |
	| UCHIJAAAA | projectred-exploration  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar            | None                                     |
	| UCHIJAAAA | rftools                 | 7.54                     | rftools-1.12-7.54.jar                           | None                                     |
	| UCHIJAAAA | rftoolscontrol          | 1.9.1                    | rftoolsctrl-1.12-1.9.1.jar                      | None                                     |
	| UCHIJAAAA | rftoolsdim              | 5.60                     | rftoolsdim-1.12-5.60.jar                        | None                                     |
	| UCHIJAAAA | rftpwroc                | 0.1                      | rftpwr_oc-0.2.jar                               | None                                     |
	| UCHIJAAAA | solarfluxreborn         | 3.50r                    | SolarFluxReborn_1.12.2-3.50r.jar                | None                                     |
	| UCHIJAAAA | stacksize               | 1.1                      | stacksize-1.12.2-1.0.jar                        | None                                     |
	| UCHIJAAAA | storagedrawers          | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
	| UCHIJAAAA | thaumcomp               | 0.3.0.16                 | ThaumicComputers-MC1.12.2-0.3.0.16.jar          | None                                     |
	| UCHIJAAAA | thedragonlib            | 1.12.2-5.2.0             | thedragonlib-1.12.2-5.2.0.jar                   | None                                     |
	| UCHIJAAAA | tow                     | 2.1.2                    | TheOneWrench-1.12.2-2.1.2.jar                   | None                                     |
	| UCHIJAAAA | thermaldynamics         | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | tinkersoc               | 0.1                      | tinkersoc-0.4.jar                               | None                                     |
	| UCHIJAAAA | tinkertoolleveling      | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
	| UCHIJAAAA | toolbelt                | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                       | None                                     |
	| UCHIJAAAA | topaddons               | 1.12.2-1.7.0             | topaddons-1.12.2-1.7.0.jar                      | None                                     |
	| UCHIJAAAA | universalmodifiers      | 1.12.2-1.0.9a            | valkyrielib-1.12.2-2.0.11a.jar                  | None                                     |
	| UCHIJAAAA | vehicle                 | 0.15.0                   | vehicle-mod-0.15.0-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | wct                     | 3.9.68                   | WirelessCraftingTerminal-1.12.2-3.9.68.jar      | None                                     |
	| UCHIJAAAA | worldedit               | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| UCHIJAAAA | wrcbe                   | 2.3.0                    | WR-CBE-1.12.2-2.3.0.27-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | xray                    | 1.4.0                    | xray-1.12.2-1.4.2.jar                           | None                                     |
	| UCHIJAAAA | yoyos                   | 1.12.2-1.2.2.20          | yoyos_1.12.2-1.2.2.20.jar                       | None                                     |
	| UCHIJAAAA | llibrary                | 1.7.14                   | llibrary-1.7.14-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | ocsensors               | 1.0.4                    | ocsensors-1.0.4-b23.jar                         | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.14                   | tesla-core-lib-1.12.2-1.0.14.jar                | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ForgelinPlugin (Forgelin-1.7.4.jar)
  
HammerCoreCore (HammerCore-1.12.2-1.9.9.17.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  c4.colytra.core.asm.ElytraTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv6-alpha-1 for Forge 14.23.3.2655
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 2045 names; 2680 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgQ2h1bmsgTG9hZGVyIGJsb2NrPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOkNodW5rTG9hZGVyPWZhbHNlDQoNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBhZGQgVGVzc2VyYWN0IGJsb2NrPyBbZGVmYXVsdDogZmFsc2VdDQogICAgQjpUZXNzZXJhY3Q9ZmFsc2UNCn0NCg0KDQpjbGllbnQgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIHJlcGxhY2UgZW5jaGFudG1lbnQgZ2xpbnQgY29sb3Igd2l0aCBtb3JlIG1hdGNoaW5nIGNvbG9ycyBmb3Igc29tZSB2YW5pbGxhIGl0ZW1zPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJDdXN0b20gRW5jaGFudG1lbnQgQ29sb3JzIGZvciBWYW5pbGxhIEl0ZW1zIj1mYWxzZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9ZmFsc2UNCg0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBNb2QgQnJvd3NlciBmZWF0dXJlIHRvIG1haW4gbWVudT8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiTW9kIEJyb3dzZXIiPWZhbHNlDQoNCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IlNtb290aCBWYW5pbGxhIEd1aXMiPWZhbHNlDQp9DQoNCg0KZGVidWcgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGFkZCBkZWJ1ZyByYXkgdHJhY2VyIGl0ZW0/IFtkZWZhdWx0OiBmYWxzZV0NCiAgICBCOlJheXRyYWNlcj1mYWxzZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgYWRkIGRlYnVnIHphcHBlciBpdGVtPyBbZGVmYXVsdDogZmFsc2VdDQogICAgQjpaYXBwZXI9ZmFsc2UNCn0NCg0KDQppdGVtcyB7DQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgYWRkIEFjY3VtdWxhdG9yIGl0ZW0/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6QWNjdW11bGF0b3I9ZmFsc2UNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgIyBTaG91bGQgSGFtbWVyQ29yZSB1c2Ugb2xkIG5ldHdvcmtpbmcgaW5zdGVhZCBvZiB0aGUgbmV3IChldmVudC1kcml2ZW4pIG9uZT8gW2RlZmF1bHQ6IGZhbHNlXQ0KICAgIEI6Ik9sZCBOZXR3b3JrIj1mYWxzZQ0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:ON, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ComputerEric'/76, l='Creative World', x=3.19, y=100.00, z=-22.94]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4836
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by EdTheDog** [comment]
BTW This crash does not happen immediately when I spawn in just like 3 seconds after...

**Comment by RlonRyan** [comment]
Already fixed in #1152

**Comment by EdTheDog** [comment]
If you're asking me how to duplicate it I just logged into my world. BUT now something even stranger is happening... So I made a new world and now I do not crash so... probably something in the old world...  BUT I cant place crop stick and get A weird error when looking at them with The One Probe...
![2018-07-03_17 12 28](https://user-images.githubusercontent.com/25651589/42250259-c6233ade-7ee4-11e8-9a7a-40df45b23ad0.png)

**Comment by EdTheDog** [comment]
BTW I hacked that cropstick in with world edit...

**Comment by EdTheDog** [comment]
Ok, wait Your comment just loaded in But... How do I fix it? I am using the newest version on curseforge but It still won't work? Do you want me to use a lower forge version or do I get the jar file from this Github if so how?

**Comment by EdTheDog** [comment]
Umm... You Still there?
